### ISSUE TITLE
I have a problem 

### ISSUE THREAD

**Issue by Quix1** [Code12x/WorldTP-For-Multiverse#18]
if I make two worlds once /mv create 1 normal and 1_nether nether and then only /editworld 1 test test tnt false then is at worldtp both worlds zusehen so: 1 and 1_nether although I have only entered that 1 is added

**Comment by Code12x** [comment]
Hello. To get only one world to show up, you must make sure that the world names are spelled the same and that the nether has "_nether" and the end has "_the_end" at the end of those world names, so that the plugin can properly recognize the dimensions for each world. 

And then you need to make sure to run "/reloadworlds" to get the world to register in the menu. And finally to edit the world's in the menu, do for example: "/editworld 1 test tnt false".

I'm sorry if I didn't answer what you were asking for. If so, please try rewording your question so I can understand it.

**Comment by Quix1** [comment]
It works thanks

**Comment by Code12x** [comment]
I'm glad I could help
